# Generated by Django 5.1.6 on 2025-06-02 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=10)),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes')),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año')),
                ('disponible', models.FloatField(blank=True, null=True, verbose_name='DISPONIBLE (LTS)')),
                ('suministro_w19', models.FloatField(blank=True, default=0, null=True)),
                ('horas_trabajo_w19', models.FloatField(blank=True, default=0, null=True)),
                ('suministro_w20', models.FloatField(blank=True, default=0, null=True)),
                ('horas_trabajo_w20', models.FloatField(blank=True, default=0, null=True)),
                ('suministro_w21', models.FloatField(blank=True, default=0, null=True)),
                ('horas_trabajo_w21', models.FloatField(blank=True, default=0, null=True)),
                ('suministro_w22', models.FloatField(blank=True, default=0, null=True)),
                ('horas_trabajo_w22', models.FloatField(blank=True, default=0, null=True)),
                ('suministro_w23', models.FloatField(blank=True, default=0, null=True)),
                ('horas_trabajo_w23', models.FloatField(blank=True, default=0, null=True)),
                ('promedio_diario_w19', models.FloatField(blank=True, editable=False, null=True)),
                ('promedio_diario_w20', models.FloatField(blank=True, editable=False, null=True)),
                ('promedio_diario_w21', models.FloatField(blank=True, editable=False, null=True)),
                ('promedio_diario_w22', models.FloatField(blank=True, editable=False, null=True)),
                ('promedio_diario_w23', models.FloatField(blank=True, editable=False, null=True)),
                ('hrs_total', models.FloatField(blank=True, editable=False, null=True)),
                ('hrs_promedio_mensual', models.FloatField(blank=True, editable=False, null=True)),
                ('nivel_combustible', models.FloatField(blank=True, editable=False, null=True)),
                ('porcentaje', models.FloatField(blank=True, editable=False, null=True)),
                ('autonomia_hrs', models.FloatField(blank=True, editable=False, null=True)),
                ('necesario_100', models.FloatField(blank=True, editable=False, null=True)),
                ('vacio_24', models.FloatField(blank=True, editable=False, null=True)),
                ('real_24', models.FloatField(blank=True, editable=False, null=True)),
                ('vacio_36', models.FloatField(blank=True, editable=False, null=True)),
                ('real_36', models.FloatField(blank=True, editable=False, null=True)),
                ('vacio_48', models.FloatField(blank=True, editable=False, null=True)),
                ('real_48', models.FloatField(blank=True, editable=False, null=True)),
                ('vacio_72', models.FloatField(blank=True, editable=False, null=True)),
                ('real_72', models.FloatField(blank=True, editable=False, null=True)),
                ('vacio_96', models.FloatField(blank=True, editable=False, null=True)),
                ('real_96', models.FloatField(blank=True, editable=False, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='estaciones.estacion')),
            ],
            options={
                'verbose_name': 'Gestión de estación',
                'verbose_name_plural': 'Gestiones de estaciones',
            },
        ),
        migrations.CreateModel(
            name='RegistroSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('consumo', models.FloatField(blank=True, null=True)),
                ('suministro', models.FloatField(blank=True, null=True)),
                ('promedio_diario', models.FloatField(blank=True, null=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_semanales', to='gestion.gestionestacion')),
            ],
            options={
                'verbose_name': 'Registro Semanal',
                'verbose_name_plural': 'Registros Semanales',
                'unique_together': {('gestion', 'semana')},
            },
        ),
    ]
