# Generated by Django 5.1.6 on 2025-05-13 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estaciones', '0004_alter_estacion_options_alter_estacion_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disponible', models.FloatField(blank=True, null=True)),
                ('nivel', models.FloatField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
                ('suministro_w19', models.FloatField(blank=True, null=True)),
                ('hrs_trabajo_w19', models.FloatField(blank=True, null=True)),
                ('promedio_diario_w19', models.FloatField(blank=True, null=True)),
                ('autonomia_hrs', models.FloatField(blank=True, null=True)),
                ('necesario_para_100', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gestion', to='estaciones.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('consumo', models.FloatField(blank=True, null=True)),
                ('suministro', models.FloatField(blank=True, null=True)),
                ('promedio_diario', models.FloatField(blank=True, null=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_semanales', to='gestion.gestion')),
            ],
            options={
                'verbose_name': 'Registro Semanal',
                'verbose_name_plural': 'Registros Semanales',
                'unique_together': {('gestion', 'semana')},
            },
        ),
    ]
