# Generated by Django 5.1.6 on 2025-05-13 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='gestion',
            name='hrs_promedio_mensual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='hrs_total',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='nivel_combustible',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
