# Generated by Django 5.1.6 on 2025-05-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_remove_gestion_observaciones_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='disponible',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='hrs_promedio_mensual',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='porcentaje',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='promedio_diario_w19',
        ),
        migrations.AddField(
            model_name='gestion',
            name='cinco_min',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='diez_min',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='total',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='veinte_min',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='autonomia_hrs',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='necesario_para_100',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='nivel_combustible',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
