# Generated by Django 5.1.6 on 2025-06-06 13:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0002_estacion_serial'),
        ('gestion', '0002_gestionestacion_historico_alarmas'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoImportado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estaciones.estacion')),
            ],
            options={
                'verbose_name': 'Evento Importado',
                'verbose_name_plural': 'Eventos Importados',
                'unique_together': {('estacion', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
