# Generated by Django 5.1.6 on 2025-06-06 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0002_estacion_serial'),
        ('gestion', '0003_eventoimportado'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstacionMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_externo', models.CharField(max_length=100)),
                ('id_externo', models.CharField(blank=True, max_length=50, null=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estaciones.estacion')),
            ],
        ),
    ]
