# Generated by Django 5.1.6 on 2025-05-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0003_remove_gestion_disponible_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestion',
            name='cinco_min',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='diez_min',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='total',
        ),
        migrations.RemoveField(
            model_name='gestion',
            name='veinte_min',
        ),
        migrations.AddField(
            model_name='gestion',
            name='disponible',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='hrs_promedio_mensual',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='nivel',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='porcentaje',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gestion',
            name='promedio_diario_w19',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='autonomia_hrs',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='necesario_para_100',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gestion',
            name='nivel_combustible',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
