# Generated by Django 5.1.6 on 2025-05-13 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0004_alter_estacion_options_alter_estacion_total'),
        ('gestion', '0004_remove_gestion_cinco_min_remove_gestion_diez_min_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GestionEstacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semana', models.CharField(max_length=10)),
                ('capacidad_anterior', models.FloatField(blank=True, null=True)),
                ('disponible', models.FloatField(blank=True, null=True)),
                ('nivel', models.FloatField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
                ('suministro', models.FloatField(blank=True, null=True)),
                ('horas_trabajo', models.FloatField(blank=True, null=True)),
                ('promedio_diario', models.FloatField(blank=True, null=True)),
                ('hrs_total', models.FloatField(blank=True, null=True)),
                ('hrs_promedio_mensual', models.FloatField(blank=True, null=True)),
                ('nivel_combustible', models.FloatField(blank=True, null=True)),
                ('autonomia_hrs', models.FloatField(blank=True, null=True)),
                ('necesario_100', models.FloatField(blank=True, null=True)),
                ('vacio_24', models.FloatField(blank=True, null=True)),
                ('real_24', models.FloatField(blank=True, null=True)),
                ('vacio_36', models.FloatField(blank=True, null=True)),
                ('real_36', models.FloatField(blank=True, null=True)),
                ('vacio_48', models.FloatField(blank=True, null=True)),
                ('real_48', models.FloatField(blank=True, null=True)),
                ('vacio_72', models.FloatField(blank=True, null=True)),
                ('real_72', models.FloatField(blank=True, null=True)),
                ('vacio_96', models.FloatField(blank=True, null=True)),
                ('real_96', models.FloatField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('estacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gestiones', to='estaciones.estacion')),
            ],
            options={
                'verbose_name': 'Gestión de estación',
                'verbose_name_plural': 'Gestiones de estaciones',
            },
        ),
        migrations.AlterField(
            model_name='registrosemanal',
            name='gestion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_semanales', to='gestion.gestionestacion'),
        ),
        migrations.DeleteModel(
            name='Gestion',
        ),
    ]
