# Generated by Django 5.1.6 on 2025-06-15 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_estacionmapping'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComentarioGestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('gestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='gestion.gestionestacion')),
            ],
        ),
    ]
