# Generated by Django 5.1.6 on 2025-05-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_gestionestacion_alter_registrosemanal_gestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionestacion',
            name='capacidad_anterior',
        ),
        migrations.RemoveField(
            model_name='gestionestacion',
            name='horas_trabajo',
        ),
        migrations.RemoveField(
            model_name='gestionestacion',
            name='nivel',
        ),
        migrations.RemoveField(
            model_name='gestionestacion',
            name='promedio_diario',
        ),
        migrations.RemoveField(
            model_name='gestionestacion',
            name='suministro',
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='horas_trabajo_w19',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='horas_trabajo_w20',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='horas_trabajo_w21',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='horas_trabajo_w22',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='promedio_diario_w19',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='promedio_diario_w20',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='promedio_diario_w21',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='promedio_diario_w22',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='suministro_w19',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='suministro_w20',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='suministro_w21',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='gestionestacion',
            name='suministro_w22',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='autonomia_hrs',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='disponible',
            field=models.FloatField(blank=True, null=True, verbose_name='DISPONIBLE (LTS)'),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='hrs_promedio_mensual',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='hrs_total',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='necesario_100',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='nivel_combustible',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='porcentaje',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='real_24',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='real_36',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='real_48',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='real_72',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='real_96',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='vacio_24',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='vacio_36',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='vacio_48',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='vacio_72',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='gestionestacion',
            name='vacio_96',
            field=models.FloatField(blank=True, editable=False, null=True),
        ),
    ]
