# Generated by Django 5.1.6 on 2025-06-15 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0005_comentariogestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanque_reserva_condenado', models.BooleanField(default=False)),
                ('tanque_base_condenado', models.BooleanField(default=False)),
                ('tanque_externo_condenado', models.BooleanField(default=False)),
            ],
        ),
    ]
