# Generated by Django 5.1.6 on 2025-06-16 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_add_semana5'),
        ('gestion', '0006_estacion'),
    ]

    operations = [
    ]
