# Generated by Django 5.1.6 on 2025-06-16 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_merge_0002_add_semana5_0006_estacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gestionestacion',
            name='promedio_diario_w23',
        ),
    ]
