# Generated by Django 5.1.6 on 2025-06-16 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0007_add_promedio_diario_w23'),
        ('gestion', '0008_remove_gestionestacion_promedio_diario_w23'),
    ]

    operations = [
    ]
