# Generated by Django 5.1.7 on 2025-06-19 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0009_merge_20250616_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentariogestion',
            name='tipo',
            field=models.CharField(default='general', max_length=20),
        ),
    ]
