# Generated by Django 5.1.7 on 2025-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0010_comentariogestion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='capacidad_maxima_reserva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
