# Generated by Django 5.1.6 on 2025-05-29 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditoria',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
