# Generated by Django 5.1.6 on 2025-05-12 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=100)),
                ('mercado', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('distribuidora', models.CharField(max_length=255)),
                ('tipo_estacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('serial', models.CharField(max_length=100)),
                ('capacidad', models.FloatField()),
                ('consumo', models.FloatField()),
                ('pac', models.CharField(max_length=100)),
                ('tanque_base', models.FloatField()),
                ('tanque_externo', models.FloatField()),
                ('total', models.FloatField()),
                ('capacidad_anterior', models.FloatField()),
                ('compens', models.FloatField()),
                ('nivel_total', models.FloatField()),
                ('cinco_min', models.FloatField()),
                ('diez_min', models.FloatField()),
                ('veinte_min', models.FloatField()),
                ('fecha', models.DateField()),
            ],
        ),
    ]
