# Generated by Django 5.1.6 on 2025-06-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estacion_id', models.IntegerField()),
                ('region', models.CharField(max_length=100)),
                ('mercado', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=255)),
                ('distribuidora', models.CharField(max_length=255)),
                ('tipo_estacion', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.FloatField()),
                ('consumo', models.FloatField()),
                ('pac', models.CharField(max_length=100)),
                ('tanque_base', models.FloatField()),
                ('tanque_externo', models.FloatField()),
                ('total', models.FloatField(blank=True, null=True)),
                ('capacidad_anterior', models.FloatField()),
                ('compens', models.FloatField(blank=True, null=True)),
                ('nivel_total', models.FloatField(blank=True, null=True)),
                ('cinco_min', models.FloatField(blank=True, null=True)),
                ('diez_min', models.FloatField(blank=True, null=True)),
                ('veinte_min', models.FloatField(blank=True, null=True)),
                ('fecha', models.DateField()),
                ('mes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes')),
                ('anio', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año')),
            ],
            options={
                'verbose_name': 'Estación',
                'verbose_name_plural': 'Estaciones',
                'unique_together': {('estacion_id', 'mes', 'anio')},
            },
        ),
    ]
