# Generated by Django 5.1.6 on 2025-06-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='serial',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
