# Generated by Django 5.1.6 on 2025-05-12 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='cinco_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='compens',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='diez_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='veinte_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
