# Generated by Django 5.1.6 on 2025-06-16 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0002_estacion_serial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='tanque_base_condenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='tanque_externo_condenado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='estacion',
            name='tanque_reserva_condenado',
            field=models.BooleanField(default=False),
        ),
    ]
