# Generated by Django 5.1.6 on 2025-05-12 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0002_alter_estacion_cinco_min_alter_estacion_compens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='nivel_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
