# Generated by Django 5.1.6 on 2025-05-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0003_alter_estacion_nivel_total'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estacion',
            options={'verbose_name': 'Estación', 'verbose_name_plural': 'Estaciones'},
        ),
        migrations.AlterField(
            model_name='estacion',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
