# Generated by Django 5.1.7 on 2025-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0003_estacion_tanque_base_condenado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='capacidad_maxima_reserva',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
