# Generated by Django 5.1.6 on 2025-05-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estaciones', '0004_alter_estacion_options_alter_estacion_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='anio',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Año'),
        ),
        migrations.AddField(
            model_name='estacion',
            name='mes',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Mes'),
        ),
    ]
